name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  conviso-sast:
    runs-on: ubuntu-latest
    container:
      image: convisoappsec/flowcli
      env:
        FLOW_API_KEY: ${{secrets.FLOW_API_KEY}}
        FLOW_PROJECT_CODE: ${{secrets.FLOW_ANALYSIS_KEY}}
    steps:
      - uses: actions/checkout@v2
      - name: Run sast
        run: flow sast run --project-code "$FLOW_PROJECT_CODE"
#      - name: Run SCA
#        run: flow sca run