name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  conviso-sast:
    runs-on: ubuntu-latest
    container:
      image: convisoappsec/flowcli
      env:
        FLOW_API_KEY: ${{secrets.FLOW_API_KEY}}
        FLOW_PROJECT_CODE: ${{secrets.FLOW_PROJECT_KEY}}
    steps:
      - uses: actions/checkout@v2
      - name: Run sast
        run: flow sast run

      - name: Run SCA
        run: flow sca run