name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  conviso-sast:
    runs-on: ubuntu-latest
    container:
      image: convisoappsec/flowcli
    steps:
      - uses: actions/checkout@v2
      - name: Run sast
        run: flow -k=${{ secrets.FLOW_API_KEY }} sast run --project-code=${{ secrets.FLOW_ANALYSIS_KEY }}

#      - name: Run SCA
#        run: flow sca run